- src/RcppPwiz.cpp
o Delete the RAMPAdapter in the pwiz backend to close additionally opened
connections (issue #64).
> Delete RAMPAdapter pointer in pwiz backend

- DESCRIPTION
- NEWS
- R/io.R
- man/openMSfile.Rd
- Change default backend to pwiz.
- Update documentation.
- Passes R CMD check.
> Make pwiz default backend (issue #84)

- DESCRIPTION
- NEWS
- R/methods-mzRpwiz.R
- inst/unitTests/test_pwiz.R
- src/RcppPwiz.cpp
- src/RcppPwiz.h
- src/RcppPwizModule.cpp
This pull request contains the new implementations for the `getScanHeaderInfo` and `getAllScanHeaderInfo` of the `pwiz` backend.
It fixes issues #106 in `mzR` and https://github.com/lgatto/MSnbase/issues/216 in `MSnbase`.
I added also a unit test to ensure that the header that is read by the new implementations matches the one which would be read using the `Ramp` backend.
> New header implementation for pwiz backend

- NEWS
- R/methods-mzRnetCDF.R
- inst/unitTests/test_cdf.R
- inst/unitTests/test_injection_time.R
- inst/unitTests/test_pwiz.R
- man/peaks.Rd
- src/RcppPwiz.cpp
- src/RcppRamp.cpp
- Add a column injectionTime to the data.frame returned by the header
function (all backends).
- Pwiz backend extracts the ion injection time.
- Update relevant documentation and add unit test(s).
This would fix (hopefully) https://github.com/lgatto/MSnbase/issues/221 . Note: injection time was first introduced in `MSnbase` due to this issue: https://github.com/lgatto/MSnbase/issues/159
> Report ion injection time in header of pwiz backend

- src/RcppPwiz.cpp
- Put try-catch conditions around the code that throws an exception if either
the analyzer, ionisation or detector is missing in the mzML file.
- Using if/else condition and check for the size of the arrays that contain the respective values does not work, since these 3 values are stored in the same array. Just checking for its `size() > 0` is thus not enough, as either one of the 3 could eventually still be missing.
> Fix for issue #113

- NEWS
- src/RcppPwiz.cpp
- Fix a problem that can cause a SEGFAULT in writeMSData/copyWriteMSData when MS
data with spectra linking to missing precursor scans is written (issue #129).
> Fix potential SEGFAULT in writeMSData/copyWriteMSData

- NEWS
- src/RcppPwiz.cpp
Ensure that precursorMz, precursorCharge and precursorIntensity are exported even if the original precursor scan is not available.
This fixes issue https://github.com/lgatto/MSnbase/issues/256
> Preserve precursor data in writeMSData

- DESCRIPTION
- NEWS
- R/io.R
- man/openMSfile.Rd
- man/peaks.Rd
If `backend` is not specified (the default), `openMsFile` selects the backend based on the file extension and eventually file content.
The relevant code was moved over from `MSnbase` and `xcms`.
Once this pull request is in `MSnbase` (and eventually `xcms`) have to be changed accordingly.
> openMSFile chooses backend based on file name and eventually file content

- DESCRIPTION
- NAMESPACE
- NEWS
- R/AllGenerics.R
- R/methods-mzRpwiz.R
- inst/unitTests/test_chromatograms.R
- man/peaks.Rd
- src/RcppPwiz.cpp
- src/RcppPwiz.h
- src/RcppPwizModule.cpp
- Add a chromatogramHeader method to extract chromatogram header information from an mzML file (issue #141).
- Unit test and documentation added.
Side note: eventually I might merit being added to the contributors of the package ;)
> Add chromatogramHeader method

- src/pwiz/utility/misc/endian.hpp
Hi, there is the fix to be able to compile on new gcc versions.
The macro for byte order is now: `__BYTE_ORDER__`
The macro for little endian is now: `__ORDER_LITTLE_ENDIAN__`
The macro for big endian is now:` __ORDER_BIG_ENDIAN__`
This pull maintains the retro-compatibility while adding new versions compatibility!
> Fix endian.hpp for new c++ versions

- R/methods-mzRnetCDF.R
- R/methods-mzRramp.R
- R/utils.R
- inst/unitTests/test_cdf.R
- inst/unitTests/test_ramp.R
- inst/unitTests/test_utils.R
- man/peaks.Rd
- src/RcppPwiz.cpp
- Add the .hasChromatograms function.
- Add chromatogram, chromatograms and chromatogramHeader methods for the ramp
and netCDF backends.
- Add related unit tests.
> Add .hasChromatograms function (issue #164)

- src/RcppPwiz.cpp
Ensure that we don't get null pointer if there is simply no chromatogram list.
> Fix issue #164 checking that chrom list is not null

- NEWS
- R/methods-mzRident.R
Fixing #181. 
`"scan.number.s." %in%  names(pars) & !is.numeric(pars[, "scan.number.s."])`
evaluates both sides of `&`, triggering the error is `scan.number.s.` is not in the data frame.
Just learned from the manpage myself:
```
‘&’ and ‘&&’ indicate logical AND and ‘|’ and ‘||’ indicate
logical OR.  The shorter form performs elementwise comparisons in
much the same way as arithmetic operators.  The longer form
evaluates left to right examining only the first element of each
vector.  Evaluation proceeds only until the result is determined.
The longer form is appropriate for programming control-flow and
typically preferred in ‘if’ clauses.
...
Yours, Steffen
> Closing #181

- DESCRIPTION
- NEWS
- R/functions-utils.R
- R/methods-mzRnetCDF.R
- R/methods-mzRramp.R
- inst/unitTests/test_cdf.R
- inst/unitTests/test_pwiz.R
- inst/unitTests/test_write.R
- man/peaks.Rd
- src/RcppPwiz.cpp
- Extract isolation window from mzML files (issue #193): data.frame returned by
jeader gains columns "isolationWindowTargetMZ", "isolationWindowLowerOffset"
and "isolationWindowUpperOffset" enabling SWATH data analysis.
- Adapt documentation and unit tests.
> Add isolationWindowTargetMZ column to header

- DESCRIPTION
- src/Makevars
Hi Steffan,
Apologies for breaking mzR so close to the release.  This patch should fix the issue in devel, and I've reverted the change in Rhdf5lib in RELEASE_3_9 so you shouldn't have to do anything to that either.
Sorry again!
> Fix issue introduced by changing quotes in Rhdf5lib::pkgconfig()

- src/RcppIdent.cpp
Suggested by @vladpetyuk for implementing mzR as a backend in the Bioconductor package [MSnID](https://www.bioconductor.org/packages/release/bioc/html/MSnID.html).
The issue is the functions `getModInfo` and `getPsmInfo` don't provide enough information to group by spectrum identification item (SII), similar to issue #155. This change adds the peptide_ref column to the output of both functions which allows grouping by SII.
> Add peptide_ref column to modification info and PSM info

- DESCRIPTION
- NEWS
- R/methods-mzRnetCDF.R
- R/zzz.R
- inst/unitTests/test_cdf.R
- inst/unitTests/test_header.R
- Fix for issue #238: ensure `header` returns the same columns for all backends.
> fix: ensure header returns the same columns for all backends

- DESCRIPTION
- NEWS
- R/methods-mzRnetCDF.R
Ensure the `header` method for the netCDF backend returns columns in correct data type.
> Ensure header for CDF backend returns columns with correct data type

- NEWS
- R/methods-mzRpwiz.R
- man/peaks.Rd
- Fix header for pwiz backend to always return a `data.frame`.
- Update documentation.
> refactor: header always returns a `data.frame` (PR #253)

- DESCRIPTION
- NEWS
- src/RcppPwiz.cpp
- Don't export/write header variables with missing values (issue #266).
> fix: mzML export
